version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    tty: true
    container_name: golang_grpc
    ports:
      - 50051:50051
